### ISSUE TITLE
There is a bug about redo function

### ISSUE THREAD

**Issue by zouzou158** [SVG-Edit/svgedit#133]
Draw 2 shapes ,  and then refresh the browser, then click the redo button,  and then you cannot draw anything

**Comment by brettz9** [comment]
While the redo is not doing anything after a refresh (especially since you didn't say to undo anything), I am not able to replicate this behavior. Please try again in our pre-release to see if you can replicate: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html

**Comment by brettz9** [comment]
Closing due to lack of response.
