### ISSUE TITLE
Write a better readme

### ISSUE THREAD

**Issue by sk-havok** [SVG-Edit/svgedit#14]
Even a few lines would be a start.
From a casual test, it appears (?) that one can simply clone the repo and then open svgedit/editor/svg-editor.html
Must one "make" before the editor is fully usable?

**Comment by codedread** [comment]
Please send a pull request with a better README :)

**Comment by ThorsenRune** [comment]
Maybe you want to elaborate on how to contribute on a readme for the uninitiated!?

**Comment by dimumurray** [comment]
> Maybe you want to elaborate on how to contribute on a readme for the uninitiated!?

It's not unreasonable for @codedread to assume users know how to make pull requests - its one of the core tenants of github as an open-source platform. In any case just google Github and pull requests. There are guides that detail how to contribute github projects. It is the internet after all...

**Comment by codedread** [comment]
I took ThorsenRune's comment as a request for some guidance on what the format / content of a README should have for SVG-edit, not a request on how a pull request works :)

Unfortunately I don't have any sage wisdom here - I haven't given a lot of thought to SVG-edit these days.  But it seems that since this request, a README file has been made:

https://github.com/SVG-Edit/svgedit/blob/master/README.md

so I'll close this issue and hope that others can make it even more awesome eventually.

**Comment by ThorsenRune** [comment]
To codedread, yes you interpreted about right. I found that SVGedit could potentially be interesting and I though about contributing, but ran into too many problems. Key issues for me was that most attempts to import SVGs fails (in the sanitizer I think).  Second It seemed dead in version 2.6 with too many bugs, I needed it for flowcharting (and I realized that the codebase is too complicated for me to find and fix the issues).  As for dimumurrays comment: feel free to be arrogant, its the internet after all....
To sk-havok, I shared your frustration and spent some time getting it up and running by trial and error. At that time I thought about making a step by step instruction for those starting from scratch sot of  install XAMPP, extract files here do this do that and so on, just to get people up and running in 30 minutes.
Best wishes
