### ISSUE TITLE
Could you please provide me the typescript library which can be used in angular 2.

### ISSUE THREAD

**Issue by yashwanthkata** [SVG-Edit/svgedit#140]
Could you please provide me the typescript library which can be used in angular 2.Hi could you please provide the option to install it as a package to use it in my angular 2 app

**Comment by waldyrious** [comment]
@yashwanthkata I think you misunderstood what this repository is for (the SVG-Edit project) and what its issues cover (bug reports / feature requests related to SVG-Edit). I'm not really sure where you might have wanted to post this, otherwise I'd try to give you some pointers. At the moment all I can think of is StackOverflow, really.
