### ISSUE TITLE
Import .sgv create by Adobe Illustrator which text  is created as paragraph can not edit

### ISSUE THREAD

**Issue by chauhd** [SVG-Edit/svgedit#15]
Hi the Author,

It's seem svgedit is not support text editor as paragraph so pls support it if you can.

Thank you!

**Comment by ThorsenRune** [comment]
I agree on this. Multiline text is a must.

**Comment by IvanSafonov** [comment]
It would be nice to realize multiline text

**Comment by brettz9** [comment]
No update on this, but I'll close the issue in favor of #190 which has some more info... Feel free to subscribe there...

**Comment by francesco-carrella** [comment]
Hello @brettz9,  is it possible that you closed both **#15** & **[#190](https://github.com/SVG-Edit/svgedit/issues/190)** cross-referencing each other so there is no issue tracking progresses on that feature / branch?
Is it frozen? Is there any plan to move it forward? Thanks for your support!

**Comment by brettz9** [comment]
@francesco-carrella : Sorry, I'm not clear regarding closing the issues. I only closed this issue no. 15; you can see #190 is still open (green at the top). Maybe you saw the red icon at the bottom of that page and thought it was closed? That was only cross-referencing to say this issue here is closed.

As far as plans to move forward, whether due to a lack of time or ability, I am only "keeping the place warm" as far as svgedit, meaning I have just been reviewing issues and PRs and doing some infrastructure improvements like moving to ES6 Modules and expanding documentation, rather than improving the core functionality or interface much myself. I am merely hoping others more qualified and who have time to concentrate on its needs will be motivated to join and make such improvements, with the core developers who originally developed svgedit having moved on. We have thankfully gotten some submissions, but no one with the skills and time has taken a significant ownership to keep the project moving forward in a systematic way.

Best wishes...
