### ISSUE TITLE
how find out current svgvalue ?

### ISSUE THREAD

**Issue by Dilipkumaryadav** [SVG-Edit/svgedit#160]
sir we are use svgeditor first select image then show in editor, not use open, import etc button so then we want to export in png not find canvas or svg current value please help me as soon as  possible

**Comment by flintforge** [comment]
Hi. I'm using the embed API of the 2.8.1 release

`setSvgString(rawString) `works fine

but

`getSvgString() `returns 
```
function (newcallback){
	  t.callbacks[cbid] = newcallback; // Set callback
	} 
```
any idea ?

**Comment by brettz9** [comment]
@flintforge : When a response is required--in the embedded API only--you must also invoke the result with a callback, e.g.:

```js
getSvgString()(function handleSvgData (data, error) {
    // Do something with the data here.
});
```
This is necessary because the `postMessage` used between frames is asynchronous, so to get a response, we need a callback.

You can take a look at the source to see how it is done: 

https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/embedapi.html

Specifically this file:

https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/embedapi-dom.js

Or in the latest pre-release:

https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/embedapi.html
https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/embedapi-dom.js

Btw, if you are looking to use cross-origin (referencing another server), there is issue #173 which we must investigate to see if a fix is possible against modern browsers.
