### ISSUE TITLE
Integration into Jupyter

### ISSUE THREAD

**Issue by riedelcastro** [SVG-Edit/svgedit#166]
Hi,

I have created a small "inline" SVG editor within [Jupyter](http://jupyter.org/) here:

https://github.com/uclmr/egal

Currently, the editor itself is something I hacked in a few days. It's not very stable or feature-rich. I would rather like to integrate something like svgedit. The user could click on some icon in the notebook cell and an svgedit window opens. After the user saves the svg within svgedit, the svg in the notebook is updated. 

I am wondering if someone has tried something like this before, whether there are some relevant code examples that could help me getting started? I have found this [documentation](https://github.com/SVG-Edit/svgedit/blob/master/docs/SvgCanvas.md) which would be my starting point. But I would be great to see some examples of other javascript projects that integrate svgedit.

**Comment by iuyiuy** [comment]
There's also the quick start guide on the wiki:
https://github.com/SVG-Edit/svgedit/wiki/Quick-start-guide

**Comment by mlamoureux** [comment]
I tried out egal and like it, especially as I need a tool for drawing quick sketches while lecturing. Quick question. When a naive user (like me) changes the cell type from "Raw NBConvert" into "Code", there seems to be no way to bring back the picture. The SVG code is all there, but it switching back to "Raw NBConvert" mode doesn't re-activate the drawing tools and does not display the picture. Any tips?

**Comment by riedelcastro** [comment]
I am currently travelling, but will look into this when back. Could you create a corresponding issue in the `egal` repository? Thanks!

**Comment by brettz9** [comment]
There are now jsdoc API docs available through the repo (for the latest release at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/docs/jsdoc/index.html ) as well as a demo using the svgcanvas.js file only (`demos/canvas.html`). Some other docs have been migrated into Markdown in the repo `docs` folder.

Closing for now due to lack of activity. Feel free to comment further, however, and also feel free to create a new page on the wiki to list your project or similar projects. Such a page might also invite other listings whose code you could explore. Thanks!
