### ISSUE TITLE
New Skin

### ISSUE THREAD

**Issue by GoTeamScotch** [SVG-Edit/svgedit#17]
I didn't like the way SVG Edit looked so I made a new theme for it. It is largely based on Photoshop CC (2015) in. Any interest in this becoming the new face of SVG Edit? If so, I'll get a pull request together sometime soon.

![SVG Edit dark theme](http://i.imgur.com/mjkUWjF.jpg)

**Comment by codedread** [comment]
I don't have a strong preference ... if you put a pull request together I can try to find time to check it out and give an opinion :)

**Comment by GoTeamScotch** [comment]
Okay right on. I'll see if I can do that sometime soon. I've modified a lot of my local copy of SVG Edit besides the skin so it might be a little while.

**Comment by ThorsenRune** [comment]
For my 2cents, rather than skins I'd prefer a  more keyboard/menu based approach.  Then again I haven't got started with svg-edit becaue of some no-go issues.
I think the Method draw skin is not bad either.

**Comment by GoTeamScotch** [comment]
A keyboard/menu approach is a different discussion entirely. I'm not a SVG Edit developer by the way, so it's not a matter of prioritizing time spent working on features for me. I already made this skin and was curious if I should share it.

What's the method draw skin?

**Comment by brettz9** [comment]
The new theme looks like a nice option to me! Great to have darker theme choices as long as readable...

Hopefully, CSS alone would be enough and our new API lets users dynamically inject stylesheets anyways, so that'd fit nicely. Let us know if there are any hooks needed to be able to handle what you need in CSS if it is not already working like this.

I'll close as this is really more of a potential PR rather than a specific feature request/bug, but feel free to submit a PR!

**Comment by Xsmael** [comment]
What has happend finally ? i'm really interested in the skin/ theming !
