### ISSUE TITLE
Converting a line to a curve doesn't appear to work.

### ISSUE THREAD

**Issue by NeilFraser** [SVG-Edit/svgedit#257]
Demo:
https://youtu.be/VqAGLb632nY

Normally I'd expect the line-to-curve feature to throw a pair of control points on the line.  I'm really not sure what's happening here.

**Comment by brettz9** [comment]
Thanks for the report.

This was fixed at least as early as alpha.4, possibly earlier or much earlier: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html

I'm closing as I've confirmed it wasn't working but is now working, though feel free to test and comment further/reopen.

Particularly with all other known regressions now being fixed in `master`, that should probably be what people should be testing against now (I just filed #258 to indicate expected remaining steps toward full release).

**Comment by Erikvv** [comment]
@brettz9 Still doesn't work in the version you linked.

**Comment by sjernigan** [comment]
Just pulled from master. Same behavior as shown in video.

**Comment by jfhenon** [comment]
https://user-images.githubusercontent.com/20402845/140663936-6805da8f-b88f-41ec-ab2b-9bff9b5bd145.mov

This is working with V7 (you have however to click on the line points to change to curve) - see video.
