### ISSUE TITLE
Please check releases

### ISSUE THREAD

**Issue by yasuokav** [SVG-Edit/svgedit#261]
https://github.com/SVG-Edit/svgedit/releases/tag/v3.0.0-alpha.4
@brettz9 `install.exe` was a malware.

@waldyrious 
```
"uploader": {
          "login": "waldyrious",
```

**Comment by waldyrious** [comment]
@yasuokav thanks for the heads-up! My account had been compromised a few days ago -- see https://github.com/opencompany/www.opencompany.org/issues/176 for more details.

I have since secured my account and cleaned up all malware-containing releases it had made during the attack period, but apparently it also appended the executable to pre-existing releases.

I'll go through all the repositories where I have commit access and delete the malware. I already did so for svg-edit. Thanks again for the warning!
