### ISSUE TITLE
Export-Import don't work

### ISSUE THREAD

**Issue by Kreminskyi** [SVG-Edit/svgedit#278]
Export-Import don't work

**Comment by brettz9** [comment]
Some fixes were made for Chrome and PDF export and applied to `master` just now.

Otherwise, you need to indicate what exactly you tried.

Node that "Import Image" refers to an SVG image, not a PNG or such.

Closing, but feel free to refile with more details if you are still seeing the issues in `master`.

**Comment by Kreminskyi** [comment]
But the previous version 2.8.1 was able to Import PNG

**Comment by brettz9** [comment]
You're right.... I've fixed it in `master`... 

----

For whatever reason, in the old code, the `offsetWidth` and `offsetHeight` we were grabbing was working to determine the image's dimensions, but it was giving 0 in our new code; I'm relying now on `naturalWidth` or `width` failing `offsetWidth`...I'd prefer to know the reason, but for whatever reason there did appear to be this difference.

I also ensured the `src` was being set after `onload` in case there could be a race condition.
