### ISSUE TITLE
Separation of CSS from JS

### ISSUE THREAD

**Issue by inspector71** [SVG-Edit/svgedit#294]
I've been looking to get into helping but have struggled with the level of simple style settings that aren't abstracted out to a style sheet.

An example would be the two main toolbars. The elements have what appear to be messy negative and positive margins set in the style attribute.

I've managed to make what I feel are simplified improvements on-the-fly via browser inspectors. I can screenshot the results and see if anyone feels the overall result is an improvement.

But what stops me from possibly issuing a (my very first!) pull request is finding where those margins are set. Significant gut grep use hasn't found the answer yet.

So this raises the question of separation of style from code. I understand there's situations where setting 'style' properties may be best done from JS but do we think it's a worthwhile goal to minimise this and perhaps (soft) 'audit' the code to separate the two as much as possible? If I can get occasional help with this, it's the sort of thing that's right up my alley, so to speak.

Thoughts?

**Comment by brettz9** [comment]
Hi there,

Sounds like a great idea, yes! And for any such questions, particularly in pursuit of a PR, feel free to ask, and if one of us can help, we can, and if we can't, we can't. :-)

Even for those situations where it may be necessary to set `style` in code such as with animations (if [CSS Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations) can't already handle them), one may define classes in CSS and then at runtime retrieve properties within these classes (such as say finding the starting and ending color of a rule defined in CSS) using the CSSOM in JavaScript and then set `style` within those parameters... (This is more of an obscure case anyways, but just mentioning it is doable even for some seemingly edge cases.)

Btw, I see plenty of places where "margin" is showing up (using Atom text editor's find-in-project feature).

**Comment by inspector71** [comment]
> Hi there,
> 
> Sounds like a great idea, yes! And for any such questions, particularly in pursuit of a PR, feel free to ask, and if one of us can help, we can, and if we can't, we can't. :-)

Thanks Brett. Really helps to have someone 'on side' if I'm to put effort into this. Personally that's more what I get out of it, motivation wise. Have been lacking that feeling of achieving something _with someone_ (partnership / teamwork) and also know that my best learning method is to bounce things off others and extrapolate. Perhaps distributed open source development is not a great journey for getting that but time will tell. 

I guess one of the issues reducing the possibility of developer interaction is maybe the lack of a forum style facility for the SVG-Edit project. It's no fun worrying that not-strictly-technical discussion in these issues may be knocked on the head. Perhaps a Sub Reddit would help?

> Even for those situations where it may be necessary to set `style` in code such as with animations (if [CSS Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations) can't already handle them), one may define classes in CSS and then at runtime retrieve properties within these classes (such as say finding the starting and ending color of a rule defined in CSS) using the CSSOM in JavaScript and then set `style` within those parameters... (This is more of an obscure case anyways, but just mentioning it is doable even for some seemingly edge cases.)

Completely agree and was thinking the same. Flipping CSS classes is preferable.

> Btw, I see plenty of places where "margin" is showing up (using Atom text editor's find-in-project feature).

Yeah it's not so much that the word `margin` does not appear, it's finding the revelant places where it appears, of course :) `git grep` is strange in a way. By default it doesn't even display line numbers in the results! FFlipS! Unlike `git diff`, `git grep` doesn't display context around results either. That's atomised development for you (each git command o  ften being a separate program instead of one integrated program). I guess that works in a lot of cases but not all. I probably need to set up `git grep` alias like `gcontext` :)

**Comment by brettz9** [comment]
> Thanks Brett. Really helps to have someone _on side_ if I'm to put effort into this. Personally that's more what I get out of it, motivation wise.

Sure... When I was first starting out, I was struck by how generous a guy I worked with (Kevin with php.js) was generous and kind in enthusiastically giving credit to contributors in a project I worked with earlier... It can be very motivating, even for someone already fairly self-motivated...

> Have been lacking that feeling of achieving something _with someone_ (partnership / teamwork) and also know that my best learning method is to bounce things off others and extrapolate. Perhaps distributed open source development is not a great journey for getting those feelings but time will tell.

There are of course some who are quite rude, and there are some, particularly at higher levels of competence, who may be eye-rollingly tiresome in their pedantry with language or requirements (as opposed to the kind of rigor that is actually useful). These people are sometimes those who may have come up with a good idea and have skill but are lazy, or who may be technical geniuses, but are too narrow in vision or don't work well with others so as to try to build something up--or if they have built something useful, they minimize what they can do be because of such weaknesses of character.

But overall, I find distributed open source development puts one into touch with people who are do-ers, who aren't so much about talk (and by this, I don't mean friendly socializing but things of little to no benefit to society like endless partisan opining), and appreciate excellence and for some, service, qualities which are hard to find concentrated locally.

And even for the people mentioned above, carefulness and ample research into an issue before taking up people's time who are not keen to share it can often allow one to get along with them to mutual benefit. And if rudeness is too much to deal with at a given time, returning to the comments at a later point when one may find the nuggets of truth scattered among them. And finding the right forums to get help or ideas.

But before we indulge too much in our observations, we probably should continue such discussions on the type of forum you mention, given that not everyone watching the project is interested in such.
 
> I guess one of the issues reducing the possibility of developer interaction is maybe the lack of a forum style facility for the SVG-Edit project. It's no fun worrying that not-strictly-technical discussion in these issues may be knocked on the head. Perhaps a Sub Reddit would help?

You might start what you like. Gitter may be a useful fit too. While I don't think it's a bad idea and in fact may help build up community, my limited energy and time is more focused on my own circumscribed areas of competence (and with a project of the scale of SVGEdit and despite my doing surface refactoring across a lot of the code, I'm still getting familiar with it). I might jump in if I have time and energy though.
 
> > Even for those situations where it may be necessary to set `style` in code such as with animations (if [CSS Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations) can't already handle them), one may define classes in CSS and then at runtime retrieve properties within these classes (such as say finding the starting and ending color of a rule defined in CSS) using the CSSOM in JavaScript and then set `style` within those parameters... (This is more of an obscure case anyways, but just mentioning it is doable even for some seemingly edge cases.)
> 
> Completely agree and was thinking the same. Flipping CSS classes is preferable.

I'm actually speaking here or more than just flipping classes, though that is no doubt the most common need, for sure. I was referring to querying what is in the CSS stylesheets from JavaScript (as opposed to what is in the DOM).

Btw, I might mention my hope with this issue (as you may already have envisioned) that such separation of concerns would use semantic class names as possible (e.g., `class="focused"` rather than `class="centered"`) to allow greater freedom on stylesheet designers. Maybe stylesheet variables would help as well (compiled to support more browsers).

> > Btw, I see plenty of places where "margin" is showing up (using Atom text editor's find-in-project feature).
> 
> Yeah it's not so much that the word `margin` does not appear, it's finding the revelant places where it appears, of course :)

Sure. Brute force of course works though, if one can't find a smarter route.

> Never thought I'd try an MS editor again since I don't really do compiled code but gave Visual Studio Code a go and it was surprisingly reasonable. Doubt I'll switch from [RJ TextEd](https://www.rj-texted.se/) but thanks for the Atom suggestion :)

Speaking of MS editors, for querying text, and doing so quickly, I found Notepad++ handy for searching across files when I was on Windows.

**Comment by jfhenon** [comment]
UI was changed in V7
