### ISSUE TITLE
"text" and "text_edit" doesn't work for setMode in SvgCanvas

### ISSUE THREAD

**Issue by Ohw222** [SVG-Edit/svgedit#324]
Hello
I'm trying to use SvgCanvas, I used the template (demo/canvas.html), I added a button like this : `<button onclick="canvas.setMode('text')">Text</button>` but when i'm using it by clicking on the canvas zone, that doesn't works.

**To Reproduce**
1. Go to the file canvas.html, edit it
2. Add the line `<button onclick="canvas.setMode('text')">Text</button>` under the 'line' one
3. Save the document and load it with a webbrowser
4. Click on the "text" button and then on the canvas area
5. See the error in your borwser's console

**Expected behavior**
I just expect that i can write some text in the textarea created

**SVG-Edit environment**
- File for SVG-Edit: `svgcanvas.js` and `canvas.html`
- Version: [e.g. 3.0.0]
- Protocol: http and https

**Desktop:**
 - OS: Tried on Solus Budgie and Windows 10
 - Browser (versions) : Chrome (72 and 73), firefox (64)

Thanks for your answers, have a nice day !
-Ohw

**Comment by brettz9** [comment]
Some initialization can be required when not using the SVG Editor. (You'd have to look through `svg-editor.js` or `svgcanvas.js` to see what is required, as the canvas independent of the editor is not documented outside of there being that basic demo.)

Investigating a little bit, the `textinput is undefined` error signals that `setInputElem` (the one place that sets the variable) hasn't been called with a text element (as it is when the full SVG editor is used).

If you add a text input element (in the editor we use an invisible element):

```html
      <input id="text" size="35" hidden="true"  />
```

...you can then pass the DOM of this in before calling `canvas.setMode('text')` (like within the last script, the init script, on the page):

```js
canvas.textActions.setInputElem($('#text')[0]);
```

(We could probably avoid the need for this by adding the input element automatically since it is hidden.)

However, this is as far as I got, as though the error disappears, and the control shows up within the canvas, the text is only present in our (hidden) input--it doesn't show up within the canvas for whatever reason. You'd have to investigate this further.

I'll close this, but it should be nice to have a more generic issue to fully document the canvas dependencies if you wanted to file such an issue (in case anyone might help).
