### ISSUE TITLE
Undo button has a bug.

### ISSUE THREAD

**Issue by shuaiyer** [SVG-Edit/svgedit#359]
**Describe the bug**
After saved the edited image,then click undo and continue edit the image,console will show Uncaught TypeError: Cannot read property 'setAttribute' of null.

**To Reproduce**
1. Edit a image and save it.
2. Click on 'Undo'
3. Use rectangle tool.

**SVG-Edit environment (IMPORTANT)**
- Version: [2.8.1]

**Desktop (please complete the following information):**
 - Browser [chrome]

**Screenshots**
![image](https://user-images.githubusercontent.com/11880590/65408616-459cdc00-de18-11e9-9f9e-e3a94fb3da6d.png)

**Additional context**

**Comment by shuaiyer** [comment]
Could anyone help me with this. Thanks a lot!

**Comment by shuaiyer** [comment]
I found 5.0.0 has the same bug, Perhaps I was not describe it clear.
1. Edit a image, just draw something and click "svg" button.
2. Click on 'Undo' button.
3. Use rectangle tool draw something.
4. See error.
![image](https://user-images.githubusercontent.com/11880590/65414755-e5616680-de26-11e9-91a7-d67f176ac25e.png)

**Comment by brettz9** [comment]
OK, I've confirmed the bug.

FYI, I edited your post to add the step of hitting "ok" (and doing nothing in the source). Hitting "Cancel" does not cause the problem.

Since I don't know that there is anyone to work on this, if you are debugging it yourself, I would suggest testing against the `svg-editor-es.html` file in a modern browser, as that is easiest to work with (and it also has the problem).

**Comment by shuaiyer** [comment]
Thanks for your suggestion, Hitting "Cancel" disabled the "Undo", perhaps this is a good way to solve this problem.

**Comment by brettz9** [comment]
We can hopefully get it fixed, but glad if it works for you as a workaround for now.

**Comment by wilkersoh** [comment]
can share with me, how do you integrate it?
After i npm install it, would you share with me how to use it?
