### ISSUE TITLE
Sometimes open new SVG doesn't complete.

### ISSUE THREAD

**Issue by ibrierley** [SVG-Edit/svgedit#4]
On Chrome 42.0.2311.135 (64-bit), if I select 'open svg' it seems to load in the svg, but continues to say 'loading image, please wait'. It doesn't seem to do this in Opera

**Comment by brettz9** [comment]
Do you still get this for the files you want to open on our current pre-release: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html ?

**Comment by mindplay-dk** [comment]
I had this problem while trying to open this file from Wikimedia:

https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg

**Comment by mindplay-dk** [comment]
Oddly, after killing the tab and reopening, it opens up with the image already open - this only happens when trying to directly open the file from the menu.

To recreate the problem, download the file from Wikimedia - open Chrome in incognito mode, then open the file via "Open SVG" in the menu. It consistently hangs. After a few a moment, reload the tab (and confirm that you want to stop the running script) and the image then opens without problems.

**Comment by jfhenon** [comment]
I could not reproduce the issue using the latest version https://svgedit.netlify.app/editor/index.html and chrome 91.0.4472.77.
I close the issue but please open a new issue if you can reproduce it.
Thanks

**Comment by mindplay-dk** [comment]
Confirmed: working in the current version. 🙂👍
