### ISSUE TITLE
How to generate documentation?

### ISSUE THREAD

**Issue by rknop** [SVG-Edit/svgedit#428]
How do you generate the documentation tree (HTML files or whatever) from the source tree?  I apologize if this is supposed to be obvious, but I've don't have a lot of experience of converting markdown files and .js source files into documentation trees in various projects, so I don't know the obvious command you run to do it.  (I'm on Linux.)

## Motivation

I just need to know how to do something that probably I'm already supposed to know how to do.

## Current behavior

There are a lot of .md files that have references to others, but you have to jump around manually.  There is some documentation in source files.  Obviously there are tools like jsdoc and/or a .md converter that integrates with it to make a documentation tree, but I don't know what they are.

## Desired behavior

I run a command, I get the HTML tree that used to be found at https://svg-edit.github.io/svgedit/releases/latest/docs/jsdoc/index.html (that page is now a 404).

## Alternatives considered

I've tried futzing around with the command-line tool jsdoc, but  I haven't used it before and haven't figured out what I need to do in the svg-edit tree to get what I'm looking for.

**Comment by brettz9** [comment]
If you perform a local install (`npm install`) after cloning the repo, you can run:

```
npm run build-docs
npm run open-docs
```

or

```
npm run build-and-open-docs
```

If you are curious, you can see in `package.json` the `jsdoc` command which these run.

Let us know if you run into any trouble with this.

Regarding the broken URL, yeah, we can hopefully find a way to get back to a state where we are hosting our docs and past versions live. Since it seems our trick to use `.gitsubmodules` for this purpose didn't work, and since I'm not sure GitHub pages has a way to allow a build step (so we don't need to follow the ugly approach of making a separate repo or bundling all of these files), I'm looking into some good free web hosting which offers build steps and integrates with GitHub. Am looking into Netlify though other suggestions are welcome.

**Comment by brettz9** [comment]
Closing as that should resolve, though feel free to comment further.

@jfhenon : Tagging you to note my comment about looking into Netlify hosting: https://github.com/SVG-Edit/svgedit/issues/428#issuecomment-674326827

**Comment by rknop** [comment]
OK, let me get this right....

I have to install a package manager to build svgedit, and to convert the documentation into something human-readable???

**Comment by brettz9** [comment]
That's currently the situation, yes (except there is no need to build svgedit just to use the editor).

If you are not happy with the situation, you can find another project, or offer a PR.

**Comment by brettz9** [comment]
@jfhenon : Re: Netlify hosting, they want the following before approving our hosting.

1. Banner or 'Powered by Netlify' link on the homepage
2. A suitable Code of Conduct. (GitHub offers one).

I'm finding myself a bit too fatigued these days to get to this. But Netlify does seem like it would let us have the build steps jsdoc requires for us to publish documentation (and the old version demos) without polluting the repo.
