### ISSUE TITLE
Vulnerabilities in svgedit dependency jquery v1.7.1?

### ISSUE THREAD

**Issue by jo-kl** [SVG-Edit/svgedit#440]
An OWASP check reports several vulnerabilities for svgedit 5.1.0, because it depends on (and includes) jquery v1.7.1:
[CVE-2012-6708](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2012-6708)
[CVE-2015-9251](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-9251)
[CVE-2019-11358](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-11358)
[CVE-2020-11022](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-11022)
[CVE-2020-11023](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-11023)

Do these security issues also exist in svgedit?
Or can the listed CVEs be safely ignored, because the affected jquery functions are never used in svgedit?

Thanks for your help.

**Comment by jfhenon** [comment]
Hello @jo-kl, we are planning to refresh (and maybe to replace) jQuery in version 6.0.0. Unfortunately no bandwidth to update svgedit 5.1.0. Is it possible for you to use 6.0.0?

**Comment by jo-kl** [comment]
Yes, we will wait for version 6.0.0. Thanks for the quick response.

**Comment by jfhenon** [comment]
It's actually a little tricky to update jQuery because some UI components are not working in recent versions of jQuery.
Indeed, you'll have to wait for a release. regarding the timing:
- we just recently finished to refresh the build process.
- Ongoing task is to make svgcanvas more manageable and easier to test (it's 7000 lines)
- next step will be to remove and/or update old dependencies (including jQuery)
At this point, I think we will be able to create a release with no security warnings.

**Comment by jfhenon** [comment]
the last master does not use an old jquery version anymore.
