### ISSUE TITLE
some tools in iframe doesnot work

### ISSUE THREAD

**Issue by kstych** [SVG-Edit/svgedit#441]
Hi , please help with fixing following

1. we have svgedit on our own servers, no issue with loading inside iframe almost everything works
2. Tools that work : Line tool,  Shape Lib, Color Picker, Star, Polygon, Panning
3. Following Tools Doesnt work (clicking on them doesnot activate)

Select, Pencil, Square, Ellipse, Path

Also I can inpect the iframe elements and see that they dont have mouse/click events on them as they are in the svg-editor without iframe

Thankyou

**Comment by jfhenon** [comment]
Hello @kstych, which version are you using for your tests?

**Comment by brettz9** [comment]
Also may want to know if the embedded API is being used or just trying to control things directly...

**Comment by kstych** [comment]
@brettz9 hi, we are just embedding the full editor within iframe (with sandbox="allow-same-origin allow-scripts allow-forms" ) which is is not generating any errors and loading all files

@jfhenon using master branch last synced following master commit
8f827c97 ("- npm: Change image optimization to "lint-staged" (passing arguments of files only)", 2020-08-05)

**Comment by jfhenon** [comment]
OK, it would be useful if you can 
1/ test on the latest build (as there are changes to the event handler going from jQuery to native events) 
2/ share an example so it's easier to reproduce it. 
Thanks
JF

**Comment by kstych** [comment]
ok, will need some time for that, we have ui changes in html that will need re-add 

thankyou for the replies will open a new one if required for the latest master branch

**Comment by kstych** [comment]
hi was able to fix this by disabling "ext-storage.js" which was causing exception in iframe loading 
exception was in function "extAndLocaleFunc"

leaving this here for everyone.

**Comment by brettz9** [comment]
Thank you, @kstych . If someone can report an exact error that might help get the issue resolved, as that extension is what allows the SVG to be remembered for next time (and asks for consent).

However, if I were to make a guess, I think it is probably the `top.location` line. You can try adding the attribute `allow-top-navigation=""` to your iframe so that the SVG editor can detect the URL parameters in your containing app, and use that to know whether to show the storage prompt.

(`allow-top-navigation-by-user-activation` could be used too but that would require a button click before the storage could be used.)
