### ISSUE TITLE
Extension structure

### ISSUE THREAD

**Issue by pathumego** [SVG-Edit/svgedit#45]
A modular system to build extensions so others could contribute more easily.

**Comment by brettz9** [comment]
What do you see as not modular about the extensions system currently?

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to comment further or reopen to provide more detail on your request. We have refactored the main code to use ES6 modules. We have some documentation to-dos, however, including for our new extension format. Feel free to check out the new release when it may be ready.
