### ISSUE TITLE
ViewBox attribute is replaced with width and height..

### ISSUE THREAD

**Issue by DKV0009** [SVG-Edit/svgedit#708]
When any SVG which has ViewBox attribute set is imported in editor, The ViewBox is replaced with width and height attributes.. This causes the svg to be non responsive when exported and used in a html page. Is there a way to stop viewbox attribute being replaced.

I have embedded SVG editor into an app and programmatically export the final image into a DIV tag, since there is no viewbox attribute the svg does not conform to the dimentions of the div it is set into.

Any pointers on how I can overcome this ??

**Comment by jfhenon** [comment]
You're right. We need to find a solution to draw responsive "svg".

**Comment by jfhenon** [comment]
https://app.bountysource.com/issues/104902756-viewbox-attribute-is-replaced-with-width-and-height

**Comment by Eharve14** [comment]
So the issue was in how the SVG is saved, the canvas is exported as an SCG string. The edit I made added the viewbox attribute to the SVG header information.

**Comment by Eharve14** [comment]
Fixed the white space error, I don't know why it passed tests on my local machine.

**Comment by Eharve14** [comment]
@jfhenon So if you look at the log file for the last failed test you can see the issue is the added view box attribute. When I tested I exported the SVG on my local machine and placed the resulting SVG into a browser to see if the image was responsive in an HTML page.

Were you actually looking for just retaining the view box if it was already there or ensuring there was a viewbox attribute in all exported photos? 

Also would you be interested in adding a tool to define a view box attribute in SVG edit? the view box does not have to be the same size as the image. 

-Eric

**Comment by Eharve14** [comment]
I could also fix the tests so that they ignore the added attribute,  if you want all exported images to have the view box attribute.

**Comment by jfhenon** [comment]
@Eharve14 
Several points:
1. Your code seems to add a viewbox with current height/width of the image. What is the behaviour if a SVG is loaded with an existing viewbox?
2. Tests are not passing because snapshots are wrong (you add viewBox="0 0 640 480") for each of them. The easiest way to fix this is to delete your snapshots on your local installation, run all tests (npm run test), this will create updated snapshots that you can commit into your PR and push to github.

**Comment by jfhenon** [comment]
@DKV0009 
You can test the PR to check if this answers to your issue at: 
https://deploy-preview-711--svgedit.netlify.app/editor/
let us know when your test is done please.

**Comment by jfhenon** [comment]
@Eharve14 
viewbox is "sanitized" when loading a new SVG:
`sanitize.js:173 sanitizeSvg: attribute viewbox in element svg not in whitelist is removed`
You need to add viewbox in the svg authorized list of attributes in sanitize.js

**Comment by Eharve14** [comment]
I have a better fix that only retains the view box imported with the image. I was more asking what behavior you were looking for, add a view box to all exported images. The current code takes the view box of the imported image and converts it to the height and width:
`// determine proper size
    if (content.getAttribute('viewBox')) {
      const viBox = content.getAttribute('viewBox')
      const vb = viBox.split(' ')
      attrs.width = vb[2]
      attrs.height = vb[3]
      svgCanvas.setViewBox();
      // handle content that doesn't have a viewBox`
This section of code is lines 530 -536
The code I added puts the view box into the definition as well as the hight and width. The next push will add a flag for has view box and only sets a view box if the imported image has a view box. The flag would allow us to add a tool to set a view box to an image.

**Comment by Eharve14** [comment]
In a later update.

**Comment by Eharve14** [comment]
So it looks like the view box attribute was mis- capitalized  in the strings. I pushed an update that fixed the sanitize method, the capitalization in the other calls to the view box. I pushed that fix first. I still think adding a tool to set the view box independently of the height and width would be cool. 

I didn't bother with the flags as this seemed to fix the issue completely.

**Comment by Eharve14** [comment]
Further testing shows that this fix also adds the view box attribute all the time because the view box attribute is added to the canvas at import. I assume that that is not the intent of this fix. I am working on flagging imported images to add or not add the view box attribute to the imported image based on whether or not they had them in the first place.
