### ISSUE TITLE
Bug: Useless and "null" attributes left in the SVG source when exporting

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [SVG-Edit/svgedit#76]
I've noticed that the output always has a border.

Here's an example of what I got :

```
<svg width="476" height="476" xmlns="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <ellipse ry="198.5" rx="198.5" id="svg_3" cy="238" cx="238" stroke-linecap="null" stroke-linejoin="null" stroke-width="0" stroke="#000000" fill="#f3f3f3"/>
 </g>
</svg>
```

When converting it to Android-file (using this tool: http://inloop.github.io/svg2android/ ) , I can see the border clearly

**Comment by codedread** [comment]
Are you saying that in SVG-edit you see the border?  Just tried your file on Chrome OSX and I don't see a border at all.

Could this be a border with the Android Drawables converter because we still have the stroke="#000000" attribute in there?

On the other hands, having those "null" values and stroke values that are not needed are not a great idea.  We should clean that up when doing the final sanitizing upon export...

**Comment by AndroidDeveloperLB** [comment]
by removing all stroke related things here, and then converting the file, I got the border removed. 
I think a color of "#000000"  is black. not transparent. 
And maybe the other values don't mean anything there. I'm not an expert in SVG and VectorDrawable (which is relatively very new).

**Comment by AndroidDeveloperLB** [comment]
I think that if the stroke-width is set to 0, it should remove any stroke related attribute.

**Comment by codedread** [comment]
Agreed - feel free to send along a patch :)

**Comment by AndroidDeveloperLB** [comment]
I know nothing about HTML5 and SVG. Sorry.
That's why I wrote about this issue here...

**Comment by codedread** [comment]
No worries and no pressure.  That's just the standard open source response for "acknowledged bug, but don't have time to work on it right now" :-)
