### ISSUE TITLE
Left hand ruler draws in wrong place when changing icon sizes

### ISSUE THREAD

**Issue by Saurbaum** [SVG-Edit/svgedit#79]
If you change the icon size to small for the controls then the left hand panel has a gap before the ruler is drawn.

**Comment by brettz9** [comment]
Replicated for small as well as large and extra-large...

**Comment by klesun** [comment]
Note, that "Small" is now the default value. The only icon size that produces correct rulers positioning is "Medium". For anyone looking for a workaround, go to the _SVG-Edit -> Editor Options_ and change "Icon size" from "Small" to "Medium".
![image](https://user-images.githubusercontent.com/5202330/76347471-634ef680-630f-11ea-9660-5bd5a6d9b1b2.png)


Also, here is a screenshot of the bug for reference:
![image](https://user-images.githubusercontent.com/5202330/76347121-c1c7a500-630e-11ea-88c7-e07ce67e0d23.png)

**Comment by klesun** [comment]
Related issue: https://code.google.com/archive/p/svg-edit/issues/507

**Comment by klesun** [comment]
And here is the issue in which resizable icons were introduced: [Resizable icons (using SVG icons)](https://code.google.com/archive/p/svg-edit/issues/63)

**Comment by klesun** [comment]
Oh well, I guess I'll just uncomment this in my `svgedit-config.es.js`:
```javascript
svgEditor.setConfig({
  // lang: '', // Set dynamically within locale.js if not previously set
  iconsize: 'm', // Will default to 's' if the window height is smaller than the minimum height and 'm' otherwise
}
```

**Comment by brettz9** [comment]
Note that the comment says "If the window height is smaller than the minimum height".

The code which determines this is this following portion of `svg-editor.js`:

```js
        const tleft = $('#tools_left');

        let minHeight;
        if (tleft.length) {
          minHeight = tleft.offset().top + tleft.outerHeight();
        }

        const size = editor.pref('iconsize');
        editor.setIconSize(size || ($(window).height() < minHeight ? 's' : 'm'));
```

IIRC, we may have changed (more recently) to a small icon size because medium icons had its own problems.

Would be really nice if we had people adding to our tests for against the nice and shiny Cypress UI + Cypress UI code coverage plugin testing framework, as we could really prevent a lot of the regressions which otherwise inevitably happen, particularly when other developers come on board.

**Comment by brettz9** [comment]
That comment could probably be better worded though to indicate the minimum height is one based on the toolbar.

Also, it seems the code above may explain the reason we changed to small; that the toolbar was ending up too large for some screens. Let us know if you find some flaws in this.

**Comment by jfhenon** [comment]
V7 has a fixed icon size.
