### ISSUE TITLE
Try to start as per documentation, get an error: Could not resolve import "@svgedit/svgcanvas"

### ISSUE THREAD

**Issue by vladimirus** [SVG-Edit/svgedit#830]
**Describe the bug**
When I follow `I want to host SVGEdit in my environment` instructions in README. I get: 
```
Error while handling server request.
PluginError: Could not resolve import "@svgedit/svgcanvas".
```

**To Reproduce**
1. Clone or copy the repository contents from github
1. run npm i to install dependencies
1. run npm run start to start a local server
1. and access http://localhost:8000/src/editor/index.html with a supported browser
1. error in the logs

**Comment by jfhenon** [comment]
Indeed, it seems the documentation is missing a step. 
Can you run `npm run build --workspace @svgedit/svgcanvas` and let us know if this solve the issue? 
I will fix the doc if you confirm.
Thanks

**Comment by vladimirus** [comment]
Yes, that worked. I ran:
Clone
npm i
npm run build --workspace @svgedit/svgcanvas

**Comment by jfhenon** [comment]
Thanks! 
I added the step in the readme.

**Comment by luisza** [comment]
Hi, I guest the problem is a  npm outdated,  for example if I try with npm 5.4   this problem happens, but if I use npm 8.15, build works.

When you use  `npm run build --workspace @svgedit/svgcanvas`  editor is not build, just svgcanvas is build.

Finally, It could be great if you can package also editor.

**Comment by jfhenon** [comment]
Yes, correct. npm workspaces are only supported with a recent npm (>7.x)
